# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jim Christie
logo: '/img/uploads/logo.jpg'
contactFormEmail: 'jim.e.christie+web-submission@gmail.com'
description: >- # this means to ignore newlines until "baseurl:"
  I'm Jim Christie. I'm a web devoloper, an agile coach, a cyclist, and sometimes, an artist. As anyone who works on the internet should, I love cats. 
  I have over five years of web development experience. I lean strongly toward back end functionality of websites. I can do design, but I don't love it and, consequently, I'm not the best at it. 
  I've become a strong supporter of agile methodologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jimirings
github_username:  jimchristie
linkedin_username: jimchristieagile
stackexchange:
  username: jimchristie
  id: "1405583"
permalink: /blog/:title/
placeholderImage: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="

# Analytics
googleAnalyticsID: 'UA-62000039-1'
smartLookID: 'a9272f39ea76e6593a0ee8b1a621aef53ebbf1fc'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  art:
    output: true
    permalink: /art/:title/
    values:
      layout: art-single

  work:
    output: true
    permalink: /work/:title/
    values:
      layout: work-single
      
  testimonials:
    output: false
  
  certifications:
    output: false
  
  trainings:
    output: false
  
  conferences:
    output: false

defaults:
  - scope:
      path: ""
      type: art
    values:
      layout: "art-single"
  - scope:
      path: ""
      type: work
    values:
      layout: "work-single"
